### ISSUE TITLE
Question re trailing \n character

### ISSUE THREAD

**Issue by MatzFan** [koic/minifyrb#1]
Just started using your excellent Gem and I have one question; presently all minified code strings end with `"\n"` - even empty ones. E.g.
```ruby
Minifyrb::Minifier.new('# comment only').minify
# => "\n"
```
I'm using `String#strip` to remove the trailing newline, as it's easier to check strings with no executable code are empty. I just wanted to check the trailing `"\n"` was the intended behavior. Thx.

**Comment by koic** [comment]
Ah, this was an oversight. Version 0.1.2 has been released. Thank you for the feedback! Enjoy!
https://github.com/koic/minifyrb/releases/tag/v0.1.2
